{
  blank_issues_enabled: false,
  contact_links:
    [
      {
        name: 'ğŸ’¡ Ideas',
        url: 'https://github.com/ServerlesslyStack/Serverlessly/discussions/categories/ideas',
        about: Request a new feature,
      },
      {
        name: 'â“ Question',
        url: 'https://github.com/ServerlesslyStack/Serverlessly/discussions/categories/q-a',
        about: Get help from community,
      },
      {
        name: 'ğŸ’¬ Other',
        url: 'https://github.com/ServerlesslyStack/Serverlessly/discussions',
        about: Other stuffs you need to discuss,
      },
    ],
}
